"""empty message

Revision ID: 442e6d8b2afa
Revises: beba386514ad
Create Date: 2019-08-07 23:14:47.993004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442e6d8b2afa'
down_revision = 'beba386514ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('eco', sa.String(), nullable=True))
    op.add_column('games', sa.Column('site', sa.String(), nullable=True))
    op.add_column('games', sa.Column('time_control', sa.String(), nullable=True))
    op.add_column('games', sa.Column('variant', sa.String(), nullable=True))
    op.add_column('players', sa.Column('lichess_username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'lichess_username')
    op.drop_column('games', 'variant')
    op.drop_column('games', 'time_control')
    op.drop_column('games', 'site')
    op.drop_column('games', 'eco')
    # ### end Alembic commands ###
