"""empty message

Revision ID: bb88962c719e
Revises: 442e6d8b2afa
Create Date: 2019-08-08 01:47:45.284624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb88962c719e'
down_revision = '442e6d8b2afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plies', 'algebraic_notation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plies', sa.Column('algebraic_notation', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
