"""empty message

Revision ID: beba386514ad
Revises: ef63ec5be611
Create Date: 2019-08-07 19:45:38.110462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beba386514ad'
down_revision = 'ef63ec5be611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('black_elo', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('white_elo', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('elo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'elo')
    op.drop_column('games', 'white_elo')
    op.drop_column('games', 'black_elo')
    # ### end Alembic commands ###
