"""empty message

Revision ID: e387ce63bc02
Revises: f9744812fed2
Create Date: 2019-08-09 00:26:09.887684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e387ce63bc02'
down_revision = 'f9744812fed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_player', 'players', ['given_name', 'surname', 'fide_id'])
    op.drop_constraint('players_fide_id_key', 'players', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('players_fide_id_key', 'players', ['fide_id'])
    op.drop_constraint('unique_player', 'players', type_='unique')
    # ### end Alembic commands ###
