"""empty message

Revision ID: ef63ec5be611
Revises: db0246ee3da4
Create Date: 2019-08-07 19:31:53.394724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef63ec5be611'
down_revision = 'db0246ee3da4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions',
    sa.Column('fen', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('fen')
    )
    op.create_table('plies',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('current_position', sa.String(), nullable=True),
    sa.Column('next_position', sa.String(), nullable=True),
    sa.Column('algebraic_notation', sa.String(), nullable=True),
    sa.Column('game_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['current_position'], ['positions.fen'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['next_position'], ['positions.fen'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plies')
    op.drop_table('positions')
    # ### end Alembic commands ###
