"""empty message

Revision ID: f9744812fed2
Revises: d789da95aa1b
Create Date: 2019-08-08 23:39:56.930773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9744812fed2'
down_revision = 'd789da95aa1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('fide_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'players', ['fide_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_column('players', 'fide_id')
    # ### end Alembic commands ###
